[project]
name = "bobafinder"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "langchain-fireworks>=1.1.0",
    "langgraph-swarm>=0.1.0",
]
